### ISSUE TITLE
I don't get my error

### ISSUE THREAD

**Issue by AspirationYC** [AspirationYC/portfolio-metadata#1]
Hi @thomasjbradley

I can't find my typo. It says I'm missing something but it is the same thing as the walkthrough.
<img width="1432" alt="Screen Shot 2019-10-20 at 9 49 10 PM" src="https://user-images.githubusercontent.com/31771017/67171165-c56c8680-f383-11e9-9e95-83872b5be50f.png">
and I don't get what does position 108 mean
<img width="505" alt="Screen Shot 2019-10-20 at 9 49 28 PM" src="https://user-images.githubusercontent.com/31771017/67171173-d1f0df00-f383-11e9-9744-515be5c7899c.png">

**Comment by thomasjbradley** [comment]
I think it’s a missing comma at the end of this line:
https://github.com/AspirationYC/portfolio-metadata/blob/gh-pages/index.html#L34

**Comment by AspirationYC** [comment]
Oh, thanks.
